NAME = weapon
FILES = main.cpp HumanA.cpp Weapon.cpp HumanB.cpp
G = g++
RM = rm -rf
FLAGS = -Wall -Wextra -Werror -std=c++98
def:
	$(G) $(FILES) -o $(NAME)
all:
	  $(G) $(FLAGS) $(FILES) -o $(NAME)
clean:
	$(RM) $(NAME)
re: clean all