NAME = harl
FILES = main.cpp Harl.cpp
G = g++
RM = rm -rf
FLAGS = -Wall -Wextra -Werror -std=c++98

$(NAME):
	  $(G) $(FLAGS) $(FILES) -o $(NAME)
all: $(NAME)

clean:
	$(RM) $(NAME)
re: clean all