NAME = zombie
FILES = main.cpp Zombie.cpp zombieHorde.cpp
G = g++
RM = rm -rf
FLAGS = -Wall -Wextra -Werror -std=c++98
default:
	$(G) $(FILES) -o $(NAME)
all:
	  $(G) $(FLAGS) $(FILES) -o $(NAME)
clean:
	$(RM) $(NAME)
re: clean all