NAME = harlFilter
FILES = main.cpp Harl.cpp
G = clang++
RM = rm -rf
FLAGS = -Wall -Wextra -Werror

$(NAME):
	  $(G) $(FLAGS) $(FILES) -o $@
all: $(NAME)

clean:
	$(RM) $(NAME)
re: clean all