
NAME = fixed
FILES = main.cpp Fixed.cpp
G = clang++
RM = rm -rf
FLAGS = -Wall -Wextra -Werror

all: $(NAME)
$(NAME):
	  $(G) $(FLAGS) $(FILES) -o $(NAME)
clean:
	$(RM) $(NAME)
re: clean all